name: ${CONTAINER_NAME}
services:
  mongo:
    image: mongo:8.0.4-rc0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - docker-network

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - docker-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - consul_data:/consul/data

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq_data:/data
    networks:
      - docker-network

  gateway:
    image: temp804/gateway:latest
    container_name: gateway
    ports:
      - "80:5000"
    environment:
      - ASPNETCORE_URLS=http://localhost:5000
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:127.0.0.1"
    networks:
      - docker-network
    command: ["dotnet", "GatewayService.dll", "--urls", "http://localhost:5000"]

  user:
    image: temp804/user:latest
    container_name: user
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://localhost:5002
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:127.0.0.1"
    networks:
      - docker-network
    command: ["dotnet", "UserService.dll", "--urls", "http://localhost:5002"]

  integration:
    image: temp804/integration:latest
    container_name: integration
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://localhost:5001
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:127.0.0.1"
    networks:
      - docker-network
    command: ["dotnet", "IntegrationService.dll", "--urls", "http://localhost:5001"]

networks:
  docker-network:
    driver: bridge

volumes:
  mongo_data:
  consul_data:
  seq_data: